project:
  type: website
  output-dir: docs

website:
  title: "Joe Kirincic"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: globe 
        href: https://bsky.app/profile/jkirincic.bsky.social
      - icon: linkedin
        href: www.linkedin.com/in/joe-kirincic-9456a970
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



